### ISSUE TITLE
Do I need to put this in startup or just run it once?

### ISSUE THREAD

**Issue by rhettadams** [xM4ddy/OFGB#12]
I accidentally ran it twice and killed both instances in task manager. I hope it didnt mess anything up but do I need to put it in startup?

**Comment by Qynklee** [comment]
No! Run as admin and check in tickbox 1 times.

**Comment by xM4ddy** [comment]
Yeah just once should be good. If something comes back you could run it again maybe.

**Comment by huzair83** [comment]
I run it everyday but it's not working. it's just saying that, o restart please. after restart still can see all the ads & more. not working.
