### ISSUE TITLE
Can we get an "apply" button that also does nothing but restart the computer

### ISSUE THREAD

**Issue by ArisuSanchez** [xM4ddy/OFGB#13]
I used the gui and didnt feel like it did anything, _even though it did_ so is it possible to add an "Apply" button that just restarts the pc?
That way it feels like it did something in a way thats more obvious?

**Comment by xM4ddy** [comment]
For most of the options it’s not actually needed! For that reason I actually did have an apply button that did that but it seemed unnecessary and an apply button restating is kinda confusing.
