### ISSUE TITLE
Clearer documentation

### ISSUE THREAD

**Issue by rnveach** [xM4ddy/OFGB#20]
It is not clear from the read me or the app itself how and when the changes are applied to a new user.

Is opening the app enough for it to apply the settings? What about if I check or uncheck the options in the app?

I couldn't find a simple explanation when glancing around. As a user, I was expecting some type of "Apply" button or a message saying the changes have been applied. It would just make things clearer if there was some signal a change occurred.

**Comment by xM4ddy** [comment]
> It is not clear from the read me or the app itself how and when the changes are applied to a new user.
> 
> Is opening the app enough for it to apply the settings? What about if I check or uncheck the options in the app?
> 
> I couldn't find a simple explanation when glancing around. As a user, I was expecting some type of "Apply" button or a message saying the changes have been applied. It would just make things clearer if there was some signal a change occurred.

Hey changes are made right after you check the box. That sets the related registry keys to the correct value. [Right here](https://github.com/xM4ddy/OFGB/blob/6829f2c7f720998a2dad17d5a85174520b56cfda/MainWindow.xaml.cs#L193) is where the code that gets run then [this code](https://github.com/xM4ddy/OFGB/blob/6829f2c7f720998a2dad17d5a85174520b56cfda/MainWindow.xaml.cs#L153) depending on what checkbox is checked (cb1 is checkbox 1) the correct keys get set. I am considering adding a green check after the check or uncheck for feedback that changes are done.

**Comment by rnveach** [comment]
Thanks. But what about when the app opens? When I opened it on my computer, some things were already checked and I didn't think I applied anything myself for those, unless my default settings happened to have them active before using this application. That's why I mentioned opening the app.

**Comment by xM4ddy** [comment]
> Thanks. But what about when the app opens? When I opened it on my computer, some things were already checked and I didn't think I applied anything myself for those, unless my default settings happened to have them active before using this application. That's why I mentioned opening the app.

The first thing the program does on startup is get the values of the different registry keys. If the key doesn’t exist it’s created and set to false. If the key does exist I just get the value. If all of the registry keys to disable ads for a particular checkbox are set it will start as checked because what the checkbox would do has already been done. If not all of the things the checkbox would set are set it’s unchecked. This means the app doesn’t disable or enable anything without the users input. Hope that makes sense!

**Comment by dimitri-dev** [comment]
@rnveach It's entirely possible that Windows enables/disables ads based on region of installation and other options.

Also, if you hadn't setup Windows yourself or installed it with a non-original image, it may contain these changes already. People have been modifying Windows images for a while now that are decluttered, "optimized" and have other changes (such as Chrome preinstalled, Edge disabled and such)
