### ISSUE TITLE
Ads in MSN Weather app

### ISSUE THREAD

**Issue by almeath** [xM4ddy/OFGB#22]
I have applied this in Windows 11 23H2 and I am still seeing ads in the "MSN Weather" app that comes bundled with Windows 11.

Can this please be addressed in an update?

**Comment by dimitri-dev** [comment]
Just chiming in here, but I am not sure that this is possible through a registry key change. Last I've heard about the Weather app is that it's basically an installed web app.

Keep in mind that blocking ads on your DNS is a valid and working option. Setting up Pi-Hole on your network does wonders :)

**Comment by almeath** [comment]
Thanks, I will look into the DNS option.
