### ISSUE TITLE
Ads in the Arcade section of Microsoft Store app.

### ISSUE THREAD

**Issue by streetwolf** [xM4ddy/OFGB#23]
When playing an Arcade game online in the Microsoft Store app a video ad will appear after playing a game for several minutes.  An example of such a game is Amazing Jewels.  Any way to get rid of these ads?

**Comment by bootsmann** [comment]
I am also playing Solitaire.exe (C:\Program Files\WindowsApps) and adds are so annoying. Blocking solitaire.exe with win firewall is working a few games. After you need to go online to continue the game...

**Comment by dimitri-dev** [comment]
Yeah... This is a no-go from what I know. They don't even let you play the game on Airplane mode on portable devices. (people used it to dodge ads)

**Comment by xM4ddy** [comment]
This isn't in this projects scope this project is focused on OS wide ads not for specific games.
