### ISSUE TITLE
The window size doesn't auto-fit the content with Windows 125% Scale and changed default font.

### ISSUE THREAD

**Issue by HumanMus1c** [xM4ddy/OFGB#25]
### Default Font: HarmonyOS Sans SC  14pt

![image](https://github.com/xM4ddy/OFGB/assets/46023154/5bc17017-61da-44fd-b563-2db865721b3b)

**Comment by xM4ddy** [comment]
Should be fixed by cd8d549dc9dbef776881cdeec5492f7081e2a602 and will be in the next release!

**Comment by HumanMus1c** [comment]
Yes, it did.

**Comment by xM4ddy** [comment]
> Yes, it did.

Awesome thanks for confirming!
