### ISSUE TITLE
Error in code: Error	CS0161	'MainWindow.CreateKey(string, string)'

### ISSUE THREAD

**Issue by EuCalare** [xM4ddy/OFGB#26]
Fixed method error:

private static bool CreateKey(string loc, string key)
{
    bool keyEnabled = false;

    if (Registry.CurrentUser.OpenSubKey(loc, true) is not null)
    {
        RegistryKey? keyRef = Registry.CurrentUser.OpenSubKey(loc, true);

        if (keyRef is not null && keyRef.GetValue(key) is null)
        {
            keyRef.SetValue(key, 0);
            keyRef.Close();
            //return false;
            keyEnabled = false;
        }
        else if (keyRef is not null)
        {
            return (Convert.ToInt32(keyRef.GetValue(key)) != 0);
        }
    }
    else
    {
        RegistryKey? keyRef = Registry.CurrentUser.CreateSubKey(loc);

        if (keyRef is not null)
        {
            keyRef.SetValue(key, 0);
            keyRef.Close();
            //return false;
            keyEnabled = false;
        }
        else
        {
            MessageBox.Show("Failed to create a registry subkey!", "Fatal Error", MessageBoxButton.OK, MessageBoxImage.Error);
            throw new InvalidOperationException("Failed to create subkey.");
        }
    }
    return keyEnabled;
}

**Comment by xM4ddy** [comment]
Fixed in latest push 7ebcaef4d7c6ce9bfb1497890beee1afefa10d7f
