### ISSUE TITLE
neither .exe doing anything?

### ISSUE THREAD

**Issue by captainmustard** [xM4ddy/OFGB#3]
I get a little loading icon next to my mouse pointer for a second and then nothing.

**Comment by Wolfeman0101** [comment]
Same issue.

**Comment by onionringostar** [comment]
same

**Comment by captainmustard** [comment]
rebooting seemed to fix it for me.

**Comment by bluearcher-bc** [comment]
same

**Comment by barryallen2023** [comment]
Same issue here. Rebooting did not fix my issues. Copy from Event Viewer. 1000 was general application error. 1026 was from .NET Runtime
[OFGB_EventID1000.txt](https://github.com/xM4ddy/OFGB/files/15182681/OFGB_EventID1000.txt)
[OFGB_EventID1026.txt](https://github.com/xM4ddy/OFGB/files/15182682/OFGB_EventID1026.txt)

**Comment by xM4ddy** [comment]
> Same issue here. Rebooting did not fix my issues. Copy from Event Viewer. 1000 was general application error. 1026 was from .NET Runtime [OFGB_EventID1000.txt](https://github.com/xM4ddy/OFGB/files/15182681/OFGB_EventID1000.txt) [OFGB_EventID1026.txt](https://github.com/xM4ddy/OFGB/files/15182682/OFGB_EventID1026.txt)

Awesome! TYSM posting the logs haha!

I think I honed in on the issue it’s on this line
https://github.com/xM4ddy/OFGB/blob/92756276178137bb78d7c563733dde0d24f13aff/MainWindow.xaml.cs#L75

I believe the fix is that I need to use CreateSubKey here in the else block to create the necessary subkeys then create the key. I’ll make that then post it here if you’re willing to give it a test.

**Comment by xM4ddy** [comment]
Hey the crashfix branch should be updated with code to fix the crash. Can someone who is having crashes build and test if it fixes the crashes for them?

**Comment by xM4ddy** [comment]
https://github.com/xM4ddy/OFGB/releases/tag/Test

**Comment by sn8k** [comment]
long loading time, but working with test

**Comment by oc-tk** [comment]
okay this version is working for me. With official one I was getting crash as well.

**Comment by xM4ddy** [comment]
Sick looks like that's the fix! Thanks For testing!

**Comment by barryallen2023** [comment]
> Hey the crashfix branch should be updated with code to fix the crash. Can someone who is having crashes build and test if it fixes the crashes for them?

Works for me.

**Comment by sharon-git** [comment]
the link:
https://github.com/xM4ddy/OFGB/releases/tag/Test is not working.
Can you please fix it?
It keeps crashing on run.
