### ISSUE TITLE
Always use VirusTotal before post something

### ISSUE THREAD

**Issue by TheCuunt** [xM4ddy/OFGB#39]
https://i.postimg.cc/tCPFXBY3/OFGB-Deps-exe-OFGB-dll-VT-3-l-71.png

"False positive" is just another lie for me.
Zero, 0 is the good "number"we want to see in VT.

**Comment by xM4ddy** [comment]
If you wish you can view the source code and compile it yourself, let my know if you find a way to get the number to 0. Otherwise feel free to show what part is malicious.
