### ISSUE TITLE
int value = !enable ? unchecked((int)0x00000001u) : unchecked((int)0x00000000u);

### ISSUE THREAD

**Issue by latop2604** [xM4ddy/OFGB#4]
Out of curiosity, what does it mean? 

Is there any differences with a simple `int value = !enable ? 1 : 0` ?

![image](https://github.com/xM4ddy/OFGB/assets/2058133/b3dd7b51-a51e-4237-8ee2-af779971079b)

**Comment by xM4ddy** [comment]
Fixed By Last Update
